spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 1
      validation-query: select 1
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

#不需要权限校验的url
auth:
  ignoreUrls:
    - /manager/login
    - /manager/login2